from TMSAnalysis.DataReduction import DataReduction
import argparse
import sys
import os

###############################################################################
# Check arguments and load inputs
if len(sys.argv) == 4:
	this_file = sys.argv[1]
	output_dir = sys.argv[2]
	config_dir = sys.argv[3]

	if output_dir[-1] != '/':
		output_dir += '/'

	if not os.path.exists(this_file):
		sys.exit('\nERROR: input file does not exist\n')

	if not os.path.exists(output_dir):
		print('No output directory found - Creating a new one')
		os.makedirs(output_dir)

else:
	print('\n\nERROR: reduce_data.py requires 3 arguments\n')
	print('Usage:')
	print('\tpython reduce_data.py <input_file> </path/to/output/directory/> </path/to/configuration/files/>')
	sys.exit('\n')


#def get_parser():
#    parser = argparse.ArgumentParser(description='Data reduction script for the Stanford TPC')
#    parser.add_argument('--inputfile', type=str, default=None, \
#                        help='path + name of input file')
#    parser.add_argument('--outputdir', type=str, default='./',\
#                        help='location to put output files')
#    parser.add_argument('--configdir', type=str, default='./', \
#                        help='location where config files are stored. '+\
#                             'Note that this must include three config files:\n'+\
#                             ' Run_Parameters,\n'+\
#                             ' Calibrations, and\n'+\
#                             ' Channel_Map')
#    parser.add_argument('--numevts', type=int, default=-1,\
#                        help='Number of events to process. If -1, run all events in the input file.')
#    parser.add_argument('--simflag', type=bool, default=False,\
#                        help='if \'True\', the input file is a simulation file '+\
#                             'generated by nexo-offline')
#    return parser


###############################################################################
#parser = get_parser()
#args = parser.parse_args()

print('\nReducing {}'.format( this_file ))
DataReduction.ReduceFile( this_file, output_dir,\
				config_dir + '/Run_Parameters_Xe_Run29_SimCompatible.csv',\
				config_dir + '/Calibrations_Xe_Run11b.csv',\
				config_dir + '/Channel_Map_Xe_Run29_MCIncluded.csv',\
				input_baseline=-1,input_baseline_rms=-1,\
				fixed_trigger=True,fit_pulse_flag=False,\
                                num_events=-1,is_simulation=False)
